dist: bionic
os: linux
language:
  - c
  - cpp
compiler:
  - gcc

addons:
  apt:
    packages:
      - cmake

before_install:
  - sudo apt -qq update
  # Needed libraries for build
  - sudo apt install libdbus-1-dev libsigc++-2.0-dev m4
  # Install dbus-launch
  - sudo apt install dbus-x11
  # Install killall command
  - sudo apt install psmisc
  # Install dbus-cxx library
  - git clone -b 0.12.0 https://github.com/dbus-cxx/dbus-cxx.git
  - cd dbus-cxx
  - cmake . && make && sudo make install
  - sudo ldconfig
  - cd ../
  # Install scan-build
  - sudo apt install clang-tools

before_script:
  # Show current versions
  - gcc --version
  - g++ --version
  - cmake --version

jobs:
  include:
    - stage: "Test local"
      script:
        # Release Build project
        - mkdir -p .build_release/ && cd .build_release/
        - cmake -DCMAKE_BUILD_TYPE=Release ../
        - make
        - cd ../
        # Debug Build project
        - mkdir -p .build_debug/ && cd .build_debug/
        - cmake -DCMAKE_BUILD_TYPE=Debug ../
        - make
        - sudo make install
        - cd ../
        # Simple binaries test
        - imu-daemon --version
        - imu-daemon --help
        - imu-client --version
        - imu-client --help
        # Start dbus
        - eval `dbus-launch --sh-syntax`
        # Execute binaries
        - imu-daemon -d
        - imu-client -a -g -t 3
        - killall imu-daemon
        - sleep 1
    - stage: "Static analyzer"
      script:
        # Static Analysis Build
        - mkdir -p .build_static_analyzer/ && cd .build_static_analyzer/
        - scan-build cmake ../
        # Run Static Analysis
        - scan-build make
