dist: bionic
os: linux
language:
  - c
  - cpp
compiler:
  - gcc

addons:
  apt:
    packages:
      - cmake

before_install:
  - sudo apt -qq update
  # Needed libraries for build
  - sudo apt install libdbus-1-dev libsigc++-2.0-dev m4
  # Install dbus-launch
  - sudo apt install dbus-x11

before_script:
  # Show current versions
  - gcc --version
  - g++ --version
  - cmake --version

jobs:
  include:
    - stage: Build
      script:
        # Install dbus-cxx library
        - git clone -b 0.12.0 https://github.com/dbus-cxx/dbus-cxx.git
        - cd dbus-cxx
        - cmake . && make && sudo make install
        - cd ../
        # build project
        - cmake .
        - make
        - LD_LIBRARY_PATH=/usr/local/lib/ ./bin/imu-client --help
        - LD_LIBRARY_PATH=/usr/local/lib/ ./bin/imu-daemon --help
    - stage: Test binaries
      script:
        # Install dbus-cxx library
        - git clone -b 0.12.0 https://github.com/dbus-cxx/dbus-cxx.git
        - cd dbus-cxx
        - cmake . && make && sudo make install
        - cd ../
        # Build project
        - cmake -DCMAKE_BUILD_TYPE=Debug .
        - make
        # Start dbus
        - eval `dbus-launch --sh-syntax`
        # Execute binaries
        - LD_LIBRARY_PATH=/usr/local/lib/ ./bin/imu-daemon -d
        - LD_LIBRARY_PATH=/usr/local/lib/ ./bin/imu-client -a -g -t 3
