dist: bionic
os: linux
language:
  - c
  - cpp
compiler:
  - gcc

addons:
  apt:
    packages:
      - cmake

before_install:
  - sudo apt -qq update
  # Needed libraries for build
  - sudo apt install libdbus-1-dev libsigc++-2.0-dev m4
  # Install dbus-launch
  - sudo apt install dbus-x11
  # Install killall command
  - sudo apt install psmisc
  # Install dbus-cxx library
  - git clone -b 0.12.0 https://github.com/dbus-cxx/dbus-cxx.git
  - cd dbus-cxx
  - cmake . && make && sudo make install && sudo ldconfig
  - cd ../
  # Install scan-build
  - sudo apt install clang-tools
  # Install python3 modules dependencies
  - sudo apt install python3-pip python3-tk
  - python3 -m pip install -r script/requirements.txt

before_script:
  # Show current versions
  - gcc --version
  - g++ --version
  - cmake --version
  - python3 --version

matrix:
  include:
    - script:
        # Release Build project
        - mkdir -p .build_release/ && cd .build_release/
        - cmake -DCMAKE_BUILD_TYPE=Release ../
        - make
        - cd ../
        # Debug Build project
        - mkdir -p .build_debug/ && cd .build_debug/
        - cmake -DCMAKE_BUILD_TYPE=Debug ../
        - make
        - sudo make install
        - sudo ldconfig
        - cd ../
        # Simple binaries test
        - imu-daemon --version
        - imu-daemon --help
        - imu-cli --version
        - imu-cli --help
        # Start dbus
        - eval `dbus-launch --sh-syntax`
        # Start IMU Daemon
        - imu-daemon -d -a2 -g250 -r500
        # Test IMU Command Line Interface
        - imu-cli -a -g -e -t 3
        # Start IMU TCP Socket as Daemon
        - imu-socket -d
        # Test IMU TCP Socket
        - python3 script/imu-dbus.py -a localhost -p 1111 -t2 -d
        # Stop All Daemons
        - killall imu-socket
        - killall imu-daemon
        - sleep 1
    - script:
        # Static Analysis Build
        - mkdir -p .build_static_analyzer/ && cd .build_static_analyzer/
        - scan-build cmake ../
        # Run Static Analysis
        - scan-build make
