name: Runtime Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  job:
    strategy:
      matrix:
        buildtype: [Debug, Release]
        samplerate: [10, 100, 500]
        gyroscale: [250, 1000]
        accelscale: [2, 16]
        sockettype: [TCP, UDP]

    runs-on: ubuntu-latest
    name: Test Application ${{ matrix.buildtype }} - SampleRate ${{ matrix.samplerate }} ms - AccelScale ${{ matrix.accelscale }} mG - GyroScale ${{ matrix.gyroscale }} °/s

    env:
      IP: localhost
      PORT: 1111
      TEST_TIME: 1

    steps:
      - name: Install dependencies
        run: |
          sudo apt install libdbus-1-dev libsigc++-2.0-dev m4 -y
          sudo apt install dbus-x11 -y
          sudo apt install psmisc -y
          sudo apt install python3-pip python3-tk -y

      - name: Install dbus-cxx
        run: |
          git clone -b 0.12.0 https://github.com/dbus-cxx/dbus-cxx.git
          cd dbus-cxx
          cmake .
          make -j$(nproc)
          sudo make install
          cd ../

      - uses: actions/checkout@v2

      - name: Install Python dependencies
        run: |
          python3 -m pip install -r script/requirements.txt

      - name: Build Project
        run: |
          mkdir -p .build/ && cd .build/
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.buildtype }} ../
          make -j$(nproc)
          sudo make install
          sudo ldconfig
          cd ../

      - name: Simple Application Test
        run: |
          imu-daemon --version
          imu-daemon --help
          imu-cli --version
          imu-cli --help
          imu-socket --version
          imu-socket --help
          python3 script/imu-dbus.py --version
          python3 script/imu-dbus.py --help

      - name: Test Application
        run: |
          eval `dbus-launch --sh-syntax`
          imu-daemon -d -a${{ matrix.accelscale }} -g${{ matrix.gyroscale }} -r${{ matrix.samplerate }}
          imu-socket -d -p $PORT -ut
          imu-cli -a -c -g -e -t$TEST_TIME
          python3 script/imu-dbus.py -a $IP -p $PORT -s ${{ matrix.sockettype }} -t$TEST_TIME -d

      - name: Stop Daemons
        run: |
          killall imu-socket
          killall imu-daemon
          sleep 1
