name: Static Analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies for Static Analysis
        run: |
          sudo apt install clang-tools

      - name: Run Static Analysis Release
        run: |
          mkdir -p .build_static_analyzer_release/ && cd .build_static_analyzer_release/
          scan-build --status-bugs cmake -DCMAKE_BUILD_TYPE=Release ../
          scan-build --status-bugs make
          cd ../

      - name: Run Static Analysis Debug
        run: |
          mkdir -p .build_static_analyzer_debug/ && cd .build_static_analyzer_debug/
          scan-build --status-bugs cmake -DCMAKE_BUILD_TYPE=Debug ../
          scan-build --status-bugs make
          cd ../
