name: Unittesting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        buildtype: [Debug, Release]

    runs-on: ubuntu-latest
    name: Unit test ${{ matrix.buildtype }} mode
    container:
      image: caiotoledo/dbuscxx:0.12.0

    steps:
      - name: Install googletest
        run: |
          git clone --branch release-1.8.1 https://github.com/google/googletest.git
          cd googletest
          cmake -DBUILD_SHARED_LIBS=ON .
          make -j$(nproc)
          sudo make install
          sudo ldconfig

      - uses: actions/checkout@v2

      - name: Run Unit Test
        run: |
          mkdir -p .build/ && cd .build/
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.buildtype }} -DBUILD_UNITTEST=1 ../
          make -j$(nproc)
          make test
