name: Unittesting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        buildtype: [Debug, Release]

    runs-on: ubuntu-latest
    name: Unit test ${{ matrix.buildtype }} mode
    container:
      image: caiotoledo/imu-rpc:latest

    env:
      TIMEOUT_UNITTEST: 5

    steps:
      - name: Install dependencies
        run: |
          apt update -qq
          apt install valgrind -y

      - uses: actions/checkout@v2

      - name: Build Project ${{ matrix.buildtype }} mode
        run: |
          mkdir -p .build_${{ matrix.buildtype }}/ && cd .build_${{ matrix.buildtype }}/
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.buildtype }} -DBUILD_UNITTEST=1 -DTIMEOUT_UNITTEST=$TIMEOUT_UNITTEST ../
          make -j$(nproc)

      - name: Run Unit Test
        run: |
          cd .build_${{ matrix.buildtype }}/
          ctest --verbose

      - name: Run Unit Test Memory Checker
        run: |
          cd .build_${{ matrix.buildtype }}/
          ctest --verbose -T memcheck
          exit $(find . -iname MemoryChecker.*.log -exec wc -l {} + | cut -f1 -d' ' | paste -sd+ | bc)
