name: Unittesting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        buildtype: [Debug, Release]

    runs-on: ubuntu-latest
    name: Unit test ${{ matrix.buildtype }} mode
    container:
      image: caiotoledo/imu-rpc:latest

    env:
      TIMEOUT_UNITTEST: 5

    steps:
      - name: Install dependencies
        run: |
          sudo apt update -qq
          sudo apt install libdbus-1-dev libsigc++-2.0-dev m4 -y
          sudo apt install valgrind -y

      - name: Install dbus-cxx
        run: |
          git clone -b 0.12.0 https://github.com/dbus-cxx/dbus-cxx.git
          cd dbus-cxx
          cmake .
          make -j$(nproc)
          sudo make install
          cd ../

      - name: Install google tests
        run: |
          git clone --branch release-1.8.1 https://github.com/google/googletest.git
          cd googletest
          cmake -DBUILD_SHARED_LIBS=ON .
          make -j$(nproc)
          sudo make install
          cd ../

      - uses: actions/checkout@v2

      - name: Build Project ${{ matrix.buildtype }} mode
        run: |
          mkdir -p .build_${{ matrix.buildtype }}/ && cd .build_${{ matrix.buildtype }}/
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.buildtype }} -DBUILD_UNITTEST=1 -DTIMEOUT_UNITTEST=$TIMEOUT_UNITTEST ../
          make -j$(nproc)

      - name: Run Unit Test
        run: |
          cd .build_${{ matrix.buildtype }}/
          ctest --verbose -T memcheck
          exit $(find . -iname MemoryChecker.*.log -exec wc -l {} + | cut -f1 -d' ' | paste -sd+ | bc)
